### ISSUE TITLE
Version 1.0.5 broke backward compatibility

### ISSUE THREAD

**Issue by tadeboro** [ServiceNowITOM/servicenow-ansible#57] opened 2021-04-19 10:27 UTC
The PR https://github.com/ServiceNowITOM/servicenow-ansible/pull/53 (or maybe was https://github.com/ServiceNowITOM/servicenow-ansible/pull/47 the source - it is hard to tell because this repo has a confusing branching strategy) contains backward-incompatible changes in the ServiceNow record modules.

The newly introduced `auth` option silently "degrades" the OAuth authentication users into using basic authentication. 

Version pin PR for the Ansible package: https://github.com/ansible-community/ansible-build-data/pull/65

**Comment by n3pjk** [comment] 2021-04-27 22:07
This was identified as a breaking upgrade made necessary to distinguish Basic, OAuth, OpenID, and any future authentication protocols. A patch can be added that, if auth is not specified but client_id is present, assume OAuth.

**Comment by tadeboro** [comment] 2021-04-27 22:59
> This was identified as a breaking upgrade made necessary to distinguish Basic, OAuth, OpenID, and any future authentication protocols. A patch can be added that, if auth is not specified but client_id is present, assume OAuth.

The problem is that this was released in a patch version. Collections should follow semantic versioning that requires a major version bump if the release contains backward-incompatible changes.

The right way forward here would probably be:

 1. Revert the change and release 1.0.6 that is backward-compatible.
 2. Reapply the change and release 2.0.0.

Alternatively (if the major version bump is not desired), the change can be reworked to simulate the 1.0.4 behavior. In this case, there is no need for 2.0.0.

/cc @willtome

**Comment by n3pjk** [comment] 2021-04-27 23:56
I'm adding the back compatibility now using the v1.0.5 tag as the baseline. I am also restoring order_by functionality to snow_record_find. I think reverting and moving to 2.0.0 makes sense.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by amittell** [comment] 2021-04-28 20:01
@n3pjk does #59 provide backward compatibility? 

If so, any reason to revert v1.0.5 and release v2.0.0 vs just releasing v1.0.6 with the backward compatibility changes? I think I prefer this route to v2.0.0 as there are no major functionality changes.

/cc @tadeboro for input

**Comment by n3pjk** [comment] 2021-04-28 20:51
The compatibility fix is in, so going to 1.0.6 works.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by n3pjk** [comment] 2021-04-28 21:36
Yes, #59 provides the backward compatibility. We can just release 1.0.6. We might want to note that 1.0.5 has a compatibility issue, though the issue is already in the 1.0.5 changelog as a break.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Closed as completed** 2021-05-28 21:39 UTC
